### ISSUE TITLE
In research window, effects list is so long "Research" button is unclickable

### ISSUE THREAD

**Issue by plague006** [matjojo/Equivalent-Exchange#1]
![Image of a young child doing a handstand](http://puu.sh/jQOKe/e5fce3f45a.jpg)
Factorio 0.12.4
Vertical resolution 1080px

Is there a keyboard shortcut others are using to research it? I'm at a loss.

**Comment by matjojo** [comment]
Ow, this is actually quite the problem, could you check what your UI settings are. it's under settings graphics.

**Comment by matjojo** [comment]
actually, after some more testing. there isn't even a reasearch button to click on the thing for screens under like 900P,(I use this resolution for testing cus of the other programs open). this will be fixed in one of the nearest patches, for now you can use the commands to research it.

**Comment by plague006** [comment]
UI scale was set to system default (100%). At ~80% UI scale the research button is fully visible.

**Comment by matjojo** [comment]
yah, I'm indeed working on it. just to set this straight. the button disappeared at my side because i had it researched already. not because of the long list.

I'm closingthis issue, Have Fun!
